### ISSUE TITLE
Terraform path error

### ISSUE THREAD

**Issue by MichalMusialPJ** [Dynatrace/Dynatrace-Config-Manager#122]
**Describe the bug**
After adding the source and destination tenant and extracting all 4 configurations, an attempt to migrate using the migrate option failed

**To Reproduce**
1. Go to Extract files
2. Click on all 4 extract config buttons
3. Scroll down to migration button and click it
4. See error (on screenshot below)

**Expected behavior**
Successful config migration

**Screenshots**
![image](https://github.com/Dynatrace/Dynatrace-Config-Manager/assets/93324928/6990b94e-f785-437d-82ff-96bcec5ecd55)

**Desktop (please complete the following information):**
 - OS: Windows 11 as VM on MAC using Parallels
 - Browser Chrome

**Comment by dcryans** [comment]
Hi, 

Thank you for your patience, I was away and didn't access GitHub for a week.

I've seen this answer on the web:
"you need to map a drive to the share or copy the files locally to run it"
From this url: 
https://forum.parallels.com/threads/executing-batch-file-in-parallels-macos.352346/

Do you think you could map a drive before starting the Config Manager
So that the Config Manager runs on a Drive instead of an UNC path?

It seems this link could help:
https://kb.parallels.com/116127


Thank you!
Please let me know if it works or not

**Comment by dcryans** [comment]
closed for inactivity
